package com.example.parentchildtoy.entity;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;

@MappedSuperclass
public class EntityBase {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, columnDefinition = "BIGINT")
    private Long id;

    @Column(updatable = false)
    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDateTime")
    protected LocalDateTime dateCreated;

    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDateTime")
    protected LocalDateTime lastUpdated;

    @PrePersist
    private void onCreate() {
        this.dateCreated = new LocalDateTime();
        this.lastUpdated = this.dateCreated;
    }

    @PreUpdate
    private void onUpdate() {
        this.lastUpdated = new LocalDateTime();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) { //mostly auto generated by Intellij except for the change noted below
            return true;
        }
        if (o == null || !(o instanceof EntityBase)) { //slightly different where Intellij uses getClass() which won't work for JPA decorated entities
            return false;
        }

        EntityBase that = (EntityBase) o;

        return getId() != null ? getId().equals(that.getId()) : that.getId() == null;
    }

    @Override
    public String toString() {
        return this.getClass().getName() + " [ID=" + id + "]";
    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}
